### ISSUE TITLE
Javaanpr syntax.xml not working

### ISSUE THREAD

**Issue by waqar17october** [oskopek/javaanpr#21] opened 2015-12-16 07:18 UTC
I have changed syntax.xml according to my country's numberplate but its not working.

   type name="pakistan"
   char content="abcdefghijklmno0pqrstuvwxyz"
   char content="abcdefghijklmno0pqrstuvwxyz"
   char content="abcdefghijklmno0pqrstuvwxyz"
   char content="o0123456789"
   char content="o0123456789"
   char content="o0123456789"
   type
   

This is my syntax.xml therefore it should only read number plate like APR420 but it also read other text on number plate like SINDH and neglects APR420. Am I missing something please help?

**Comment by oskopek** [comment] 2015-12-17 15:17
Some ideas:

* Are you sure you're using the correct syntax.xml file?
* The algorithm doesn't work 100% (no such algorithm does, currently), you can't expect it to work 100% correctly :)
* Take a look at this StackOverflow question and answer: http://stackoverflow.com/a/18689437/2713162

**Comment by oskopek** [comment] 2015-12-18 14:13
Waqar's email:

Hello
Your response to my query was very helpful as I was able to run syntax.xml file. But sorry for bothering you again there is another issue i.e
My syntax.xml file is
 
```xml
<?xml version="1.0" encoding="iso-8859-2"?>
 
<structure>
 
 
<type name="SINDH">
<char content="abcdefghijklmno0pqrstuvwxyz"/>
<char content="abcdefghijklmno0pqrstuvwxyz"/>
<char content="abcdefghijklmno0pqrstuvwxyz"/>
<char content="o0123456789"/>
<char content="o0123456789"/>
<char content="o0123456789"/>
<char content="o0123456789"/>
</type>
 
　
　
　
</structure>
 ```

Now issue is this that 3rd char content contains only alphabets but it reads third character sometimes as 8 while 8 is not listed in 3rd char content of syntax.xml. For example it reads ARB-420 number plate as AR8420 or sometimes reads it as ARF4Z0 while Z is not in 5th char context in syntax.xml. Kindly help
 
Regards,
Waqar Ahmed

**Comment by oskopek** [comment] 2015-12-18 14:16
The likely cause of this is the `-` character. Your syntax.xml file seems to contain 3 characters and then 4 digits, although your plates only have 3 characters, a dash and 3 digits.

Suggestions:

* remove the first digit from your syntax.xml
* replace it with a "dash", or nothing

**Comment by waqar17october** [comment] 2015-12-18 14:36
You havn't understood my issue.
AFR420 should not be red as AFR4ZO as 5th char content doesnot contain Z it only contain numerical digits. I have done what you have said limited my syntax.xml to 6 char contents but results are same.

**Comment by oskopek** [comment] 2015-12-20 13:54
Hmm, that is weird. Are you sure you're loading the right syntax.xml? Mind posting a sample image, so I can try it out (and possibly fix it)?

**Comment by waqar17october** [comment] 2015-12-21 03:44
![snz-6320_20151219083737](https://cloud.githubusercontent.com/assets/16317238/11922978/762fe5a8-a751-11e5-9754-fef5a6d4347c.jpg)

This is sample image and syntax.xml is 

<?xml version="1.0" encoding="iso-8859-2"?>

<structure>
 

<type name="SINDH">
   <char content="abcdefghijklmno0pqrstuvwxyz"/>
   <char content="abcdefghijklmno0pqrstuvwxyz"/>
   <char content="abcdefghijklmno0pqrstuvwxyz"/>
   <char content="o0123456789"/>
   <char content="o0123456789"/>
   <char content="o0123456789"/>
   
   </type>


</structure>

Its reading it as AR8420 while it should not make 3rd char as 8 because 8 is not included in 3rd char content of syntax.xml. Kindly help me out

**Comment by waqar17october** [comment] 2015-12-21 06:27
Kindly also tell me how to read number plates which are two lined i.e. 
![la](https://cloud.githubusercontent.com/assets/16317238/11924661/c794d6d0-a768-11e5-941f-2a29e1e260ff.jpg)

How will I modify my syntax.xml to read this. Please help

**Comment by oskopek** [comment] 2015-12-21 19:08
@waqar17october: If I remember correctly, number plates with two lines will not work in JavaANPR by design.

As to the syntax.xml problem, I'm looking into it.

**Comment by oskopek** [comment] 2015-12-25 13:56
@waqar17october regarding AFR420: I cannot seem to reproduce your problem. I'll try with your custom syntax.xml
![screenshot from 2015-12-25 14-55-05](https://cloud.githubusercontent.com/assets/1811716/12003252/9d3a885a-ab17-11e5-96be-e68f7aa3a725.png)

**Comment by oskopek** [comment] 2015-12-25 14:01
Can't reproduce even with your own syntax xml. Are you sure you set the correct syntax xml in `config.xml`?

Proof:
![screenshot from 2015-12-25 14-59-22](https://cloud.githubusercontent.com/assets/1811716/12003277/4272bd6a-ab18-11e5-9d52-3710a9d02ac3.png)

**Comment by waqar17october** [comment] 2015-12-28 04:30
Thanku for your so much interest.
Can we somehow edit JavaAnpr to read 2 lined number plates? If yes kindly tell me how?

**Comment by oskopek** [comment] 2015-12-28 09:27
@waqar17october it sure is possible, but I'm not really sure how right off the bat. If you try to do it on your own, use this for help: [Original author's documentation](http://javaanpr.sourceforge.net/anpr.pdf)

**Comment by waqar17october** [comment] 2015-12-28 09:50
Ok

**Comment by oskopek** [comment] 2016-02-09 14:48
Closing as invalid.

**Closed by oskopek** 2016-02-09 14:48 UTC
Labels: invalid
